# Generated by Django 4.0.5 on 2022-06-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
